[package]
name = "actix-fbr"
version = "0.1.0"
edition = "2021"
authors = ["Artemiy Boykov aka Arhimondus", "<arhimondus@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.49"
proc-quote = "0.4.0"
quote = "*"